import { airportsList } from "../../airport-lambda/airPortData/data";
import { Flight } from "../interfaces/flight";
export const flightsList: Flight[] = [
    {
        id: 1,
        startAirport: airportsList[0],
        destinationAirport: airportsList[1],
        departureTime: "",
        arrivalTime: "",
        price: 100,
    },
    {
        id: 2,
        startAirport: airportsList[0],
        destinationAirport: airportsList[1],
        departureTime: "",
        arrivalTime: "",
        price: 120,
    },
    {
        id: 3,
        startAirport: airportsList[0],
        destinationAirport: airportsList[1],
        departureTime: "",
        arrivalTime: "",
        price: 220,
    },
    {
        id: 4,
        startAirport: airportsList[1],
        destinationAirport: airportsList[0],
        departureTime: "",
        arrivalTime: "",
        price: 200,
    },
    {
        id: 5,
        startAirport: airportsList[1],
        destinationAirport: airportsList[0],
        departureTime: "",
        arrivalTime: "",
        price: 140,
    },
    {
        id: 6,
        startAirport: airportsList[1],
        destinationAirport: airportsList[0],
        departureTime: "",
        arrivalTime: "",
        price: 125,
    },
    {
        id: 7,
        startAirport: airportsList[0],
        destinationAirport: airportsList[1],
        departureTime: "",
        arrivalTime: "",
        price: 420,
    },
    {
        id: 8,
        startAirport: airportsList[0],
        destinationAirport: airportsList[1],
        departureTime: "",
        arrivalTime: "",
        price: 420,
    },
    {
        id: 9,
        startAirport: airportsList[0],
        destinationAirport: airportsList[1],
        departureTime: "",
        arrivalTime: "",
        price: 420,
    },
    {
        id: 10,
        startAirport: airportsList[0],
        destinationAirport: airportsList[1],
        departureTime: "",
        arrivalTime: "",
        price: 420,
    },
    {
        id: 11,
        startAirport: airportsList[0],
        destinationAirport: airportsList[1],
        departureTime: "",
        arrivalTime: "",
        price: 420,
    },
];
